version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_judge
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  piper-tts:
    image: rhasspy/piper-http-server
    command: ["--model", "en_US-lessac-medium"]
    ports:
      - "5002:5000"
    restart: unless-stopped

  ai-service:
    build:
      context: ./ai-service
    restart: always
    ports:
      - "50051:50051"
    env_file:
      - .env
    environment:
      - PIPER_TTS_URL=http://piper-tts:5000

  backend:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/online_judge?sslmode=disable
      - REDIS_URL=redis:6379
      - AI_SERVICE_URL=ai-service:50051
      - PORT=8080
      - HOST_PWD=/home/ubuntu/online-judge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./problems:/app/problems
      - ./server/workers/submissions:/app/server/workers/submissions
    depends_on:
      - db
      - redis
      - ai-service

volumes:
  pgdata:
  redisdata:
